stages:
  - build

build:
  image: thinhbuzz/pnpm:9.15.4
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  stage: build
  script:
    - pnpm link --global
  only:
    - master

